# the port of server
server:
  port: 4321

# spring setting
spring:
  #redis
  redis:
    cluster:
      nodes: 10.10.2.233:7000,10.10.2.233:7001,10.10.2.233:7002,10.10.2.233:7003,10.10.2.233:7004,10.10.2.233:7005
    timeout: 1000
    pool:
      max-active: 20
      max-idle: 8
      min-idle: 2
      max-wait: 10
  # mysql
  datasource:
    url: jdbc:mysql://47.98.104.252:3306/spring_rookie?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&useCursorFetch=true&useSSL=false
    username: root
    password: Root@3306
  # view
  thymeleaf:
    prefix: classpath:/web/
    suffix: .html
    mode: HTML5
    content-type: text/html
    cache: false



# mybatis setting
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*.xml
  #type-aliases-package: com.pkgs.entity

# logback
logging:
  config: classpath:setting/logback.xml

# my
my:
  name: cs12110
  age: 36
  gender: male